# 通用配置
runmode: debug               # Gin 开发模式, 可选值有：debug, release, test
addr: :8080                  # HTTP 服务器监听地址

# MySQL 数据库相关配置
db:
  host: 127.0.0.1  # MySQL 机器 IP 和端口，默认 127.0.0.1:3306
  username: miniblog # MySQL 用户名(建议授权最小权限集)
  password: miniblog1234 # MySQL 用户密码
  database: miniblog # miniblog 系统所用的数据库名
  max-idle-connections: 100 # MySQL 最大空闲连接数，默认 100
  max-open-connections: 100 # MySQL 最大打开的连接数，默认 100
  max-connection-life-time: 10s # 空闲连接最大存活时间，默认 10s
  log-level: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info

# 日志配置
log:
  disable-caller: false
  disable-stacktrace: false
  level: debug
  format: console
  output-paths: [/tmp/miniblog.log, stdout]